// Code generated by MockGen. DO NOT EDIT.
// Source: validator.go

// Package mockpbft is a generated GoMock package.
package mockpbft

import (
	protocol "github.com/chain5j/chain5j-pbft/protocol"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockValidator is a mock of Validator interface
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
}

// MockValidatorMockRecorder is the mock recorder for MockValidator
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// ID mocks base method
func (m *MockValidator) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID
func (mr *MockValidatorMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockValidator)(nil).ID))
}

// String mocks base method
func (m *MockValidator) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String
func (mr *MockValidatorMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockValidator)(nil).String))
}

// MockValidatorSet is a mock of ValidatorSet interface
type MockValidatorSet struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorSetMockRecorder
}

// MockValidatorSetMockRecorder is the mock recorder for MockValidatorSet
type MockValidatorSetMockRecorder struct {
	mock *MockValidatorSet
}

// NewMockValidatorSet creates a new mock instance
func NewMockValidatorSet(ctrl *gomock.Controller) *MockValidatorSet {
	mock := &MockValidatorSet{ctrl: ctrl}
	mock.recorder = &MockValidatorSetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockValidatorSet) EXPECT() *MockValidatorSetMockRecorder {
	return m.recorder
}

// CalcProposer mocks base method
func (m *MockValidatorSet) CalcProposer(lastProposer string, round uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CalcProposer", lastProposer, round)
}

// CalcProposer indicates an expected call of CalcProposer
func (mr *MockValidatorSetMockRecorder) CalcProposer(lastProposer, round interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalcProposer", reflect.TypeOf((*MockValidatorSet)(nil).CalcProposer), lastProposer, round)
}

// GetProposer mocks base method
func (m *MockValidatorSet) GetProposer() protocol.Validator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProposer")
	ret0, _ := ret[0].(protocol.Validator)
	return ret0
}

// GetProposer indicates an expected call of GetProposer
func (mr *MockValidatorSetMockRecorder) GetProposer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProposer", reflect.TypeOf((*MockValidatorSet)(nil).GetProposer))
}

// IsProposer mocks base method
func (m *MockValidatorSet) IsProposer(id string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProposer", id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsProposer indicates an expected call of IsProposer
func (mr *MockValidatorSetMockRecorder) IsProposer(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProposer", reflect.TypeOf((*MockValidatorSet)(nil).IsProposer), id)
}

// Policy mocks base method
func (m *MockValidatorSet) Policy() protocol.ProposerPolicy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Policy")
	ret0, _ := ret[0].(protocol.ProposerPolicy)
	return ret0
}

// Policy indicates an expected call of Policy
func (mr *MockValidatorSetMockRecorder) Policy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Policy", reflect.TypeOf((*MockValidatorSet)(nil).Policy))
}

// GetByIndex mocks base method
func (m *MockValidatorSet) GetByIndex(index uint64) protocol.Validator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIndex", index)
	ret0, _ := ret[0].(protocol.Validator)
	return ret0
}

// GetByIndex indicates an expected call of GetByIndex
func (mr *MockValidatorSetMockRecorder) GetByIndex(index interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIndex", reflect.TypeOf((*MockValidatorSet)(nil).GetByIndex), index)
}

// GetById mocks base method
func (m *MockValidatorSet) GetById(id string) (int, protocol.Validator) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(protocol.Validator)
	return ret0, ret1
}

// GetById indicates an expected call of GetById
func (mr *MockValidatorSetMockRecorder) GetById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockValidatorSet)(nil).GetById), id)
}

// AddValidator mocks base method
func (m *MockValidatorSet) AddValidator(id string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddValidator", id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AddValidator indicates an expected call of AddValidator
func (mr *MockValidatorSetMockRecorder) AddValidator(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddValidator", reflect.TypeOf((*MockValidatorSet)(nil).AddValidator), id)
}

// RemoveValidator mocks base method
func (m *MockValidatorSet) RemoveValidator(id string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveValidator", id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// RemoveValidator indicates an expected call of RemoveValidator
func (mr *MockValidatorSetMockRecorder) RemoveValidator(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveValidator", reflect.TypeOf((*MockValidatorSet)(nil).RemoveValidator), id)
}

// List mocks base method
func (m *MockValidatorSet) List() []protocol.Validator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]protocol.Validator)
	return ret0
}

// List indicates an expected call of List
func (mr *MockValidatorSetMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockValidatorSet)(nil).List))
}

// Size mocks base method
func (m *MockValidatorSet) Size() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Size")
	ret0, _ := ret[0].(int)
	return ret0
}

// Size indicates an expected call of Size
func (mr *MockValidatorSetMockRecorder) Size() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Size", reflect.TypeOf((*MockValidatorSet)(nil).Size))
}

// Copy mocks base method
func (m *MockValidatorSet) Copy() protocol.ValidatorSet {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Copy")
	ret0, _ := ret[0].(protocol.ValidatorSet)
	return ret0
}

// Copy indicates an expected call of Copy
func (mr *MockValidatorSetMockRecorder) Copy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Copy", reflect.TypeOf((*MockValidatorSet)(nil).Copy))
}

// FaultTolerantNum mocks base method
func (m *MockValidatorSet) FaultTolerantNum() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FaultTolerantNum")
	ret0, _ := ret[0].(int)
	return ret0
}

// FaultTolerantNum indicates an expected call of FaultTolerantNum
func (mr *MockValidatorSetMockRecorder) FaultTolerantNum() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FaultTolerantNum", reflect.TypeOf((*MockValidatorSet)(nil).FaultTolerantNum))
}
